"""

Problem 2:
Even Fibonacci numbers:


Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million (4000000),
find the sum of the even-valued terms.

Answer:  4613732

TIPS: Fn = Fn-1 + Fn-2

"""

"""
# solution 1............................................................................
first_number = 0
second_number = 1
total = 0

while second_number < 4000000:
    first_number, second_number = second_number, first_number + second_number
    if second_number % 2 == 0:
        total = second_number + total
        print(total)
"""
"""
# solution 2.............................................................................
x = 0
y = 1
fibonacci_series = []
even_fibonacci_series = []
odd_fibonacci_series = []

sum_fibonacci_series = 0
sum_even_fibonacci_series = 0
sum_odd_fibonacci_series = 0

while y < 4000000:
    x, y = y, x+y
    fibonacci_series.append(y)
    sum_fibonacci_series = sum_fibonacci_series + y

    if y % 2 == 0:
        even_fibonacci_series.append(y)
        sum_even_fibonacci_series = sum_even_fibonacci_series + y
    else:
        odd_fibonacci_series.append(y)
        sum_odd_fibonacci_series = sum_odd_fibonacci_series + y

print('Fibonacci series: ', fibonacci_series)
print('Total items in fibonacci series: ', len(fibonacci_series))
print('Total of the fibonacci: ', sum_fibonacci_series)


print('Even fibonacci series: ', even_fibonacci_series)
print('Total even items in fibonacci series: ', len(even_fibonacci_series))
print('Sum of even fibonacci series: ', sum_even_fibonacci_series)

print('Odd fibonacci series: ', odd_fibonacci_series)
print('Total odd items in fibonacci series: ', len(odd_fibonacci_series))
print('Sum of odd fibonacci series: ', sum_odd_fibonacci_series)

"""


# solution 3...........................................................................

def fibonacci(n):
    series = []
    a = 0
    b = 1

    if n < 0:
        print('Incorrect input!')

    elif n == 0:
        return 0
    elif n == 1 or n == 2:
        return 1
    else:
        for i in range(1, n):
            temp = a + b
            a = b
            b = temp
            series.append(b)

        return series


print(fibonacci(10))
